### ISSUE TITLE
Train ML models to detect all other objects detect by the system 

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#18]
Find proper data and training for objects detection from a camera in the corner of the room perspective.

**Comment by Abdumbo99** [comment]
Add sub-tasks as you see necessary

**Comment by esattok** [comment]
https://github.com/esattok/vanny/issues/17#issuecomment-1529109429

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="328" alt="Screen Shot 2023-05-06 at 23 54 15" src="https://user-images.githubusercontent.com/86562400/236672549-e31b60eb-2846-4abf-b3fe-d458ed52e5ab.png">
<img width="301" alt="Screen Shot 2023-05-06 at 23 53 17" src="https://user-images.githubusercontent.com/86562400/236672558-f2c53595-34e0-48cf-8d68-e0c74f48f9fe.png">
<img width="399" alt="Screen Shot 2023-05-06 at 23 53 53" src="https://user-images.githubusercontent.com/86562400/236672567-812db304-882c-4074-8c28-1e192870052f.png">
