### ISSUE TITLE
Train a ML model to detect a toddler

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#47]
Lvl of #17

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="177" alt="Screen Shot 2023-05-07 at 01 08 21" src="https://user-images.githubusercontent.com/86562400/236672424-322e1b64-6356-425f-9e6e-8b47fc0d51df.png">
<img width="172" alt="Screen Shot 2023-05-07 at 01 08 04" src="https://user-images.githubusercontent.com/86562400/236672426-86502d50-f0e5-41d8-a364-315b53c5dbe2.png">
<img width="183" alt="Screen Shot 2023-05-07 at 01 07 53" src="https://user-images.githubusercontent.com/86562400/236672430-24c09bc0-3306-4d01-86a7-0ab8161d8257.png">
<img width="399" alt="Screen Shot 2023-05-06 at 23 53 53" src="https://user-images.githubusercontent.com/86562400/236672436-48ea35ec-79cc-43f8-8565-58a6e0853dc2.png">
<img width="274" alt="Screen Shot 2023-05-06 at 23 52 15" src="https://user-images.githubusercontent.com/86562400/236672447-0128d32d-f6e5-483c-9ab0-22109d5fa455.png">
