### ISSUE TITLE
Detect toddlers in their lightly illuminated bedroom with +50% accuracy

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#50]
Detect toddlers in their lightly illuminated bedroom with +50% accuracy. child of #49

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="301" alt="Screen Shot 2023-05-06 at 23 53 17" src="https://user-images.githubusercontent.com/86562400/236672344-b81ee216-563f-4317-bce5-106ea0d2766f.png">
