### ISSUE TITLE
Detect toddlers in their lightly illuminated bedroom with +75% accuracy. 

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#51]
Detect toddlers in their lightly illuminated bedroom with +75% accuracy. child of #49

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="336" alt="Screen Shot 2023-05-06 at 23 53 00" src="https://user-images.githubusercontent.com/86562400/236672313-a310e818-e62b-46cb-917a-4b2bc2513d30.png">

<img width="324" alt="Screen Shot 2023-05-06 at 23 53 33" src="https://user-images.githubusercontent.com/86562400/236672319-ea5fbf5c-356d-445e-bbbf-a7bd5beb3063.png">
