### ISSUE TITLE
Detect toddlers in their lightly illuminated bedroom with +90% accuracy.  

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#52]
Detect toddlers in their lightly illuminated bedroom with +90% accuracy. child of #49

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="177" alt="Screen Shot 2023-05-07 at 01 08 21" src="https://user-images.githubusercontent.com/86562400/236672284-06687ed9-a3be-4206-a091-199a230050f6.png">

<img width="183" alt="Screen Shot 2023-05-07 at 01 07 53" src="https://user-images.githubusercontent.com/86562400/236672288-d78fe23e-0bf5-4902-bb6b-b54ba43a3235.png">

<img width="172" alt="Screen Shot 2023-05-07 at 01 08 04" src="https://user-images.githubusercontent.com/86562400/236672293-0496c6ff-e0a4-4303-bd72-5db45d8df51d.png">
