### ISSUE TITLE
Detect three sharp objects with acceptable accuracy

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#56]
Detect three sharp object of interest with an acceptable accuracy (+50%, +75%,+90%). child of #18

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="336" alt="Screen Shot 2023-05-06 at 23 53 00" src="https://user-images.githubusercontent.com/86562400/236671981-d7588f91-0520-4497-8a5d-d3bdfedce9ac.png">

<img width="399" alt="Screen Shot 2023-05-06 at 23 53 53" src="https://user-images.githubusercontent.com/86562400/236671995-b9afffcf-0c1f-48ef-9b57-490915668e70.png">

<img width="328" alt="Screen Shot 2023-05-06 at 23 54 15" src="https://user-images.githubusercontent.com/86562400/236672007-7277c85e-4f8b-4b82-b1f4-38198f0452d0.png">

<img width="301" alt="Screen Shot 2023-05-06 at 23 53 17" src="https://user-images.githubusercontent.com/86562400/236672026-2f0fa60b-9411-4a7b-b95e-09f5af7044a6.png">
