### ISSUE TITLE
Detect seconds sharp object of interest with a +50% accuracy.  

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#61]
Detect second sharp object of interest with a +50% accuracy.  child of #57

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="148" alt="Screen Shot 2023-05-07 at 13 17 35" src="https://user-images.githubusercontent.com/86562400/236671617-dacd021d-7977-4cf8-969e-9dfd0851ca8d.png">
