### ISSUE TITLE
Detect second sharp object of interest with a +75% accuracy.  

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#64]
Detect second sharp object of interest with a +75% accuracy.  child of #58

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="150" alt="Screen Shot 2023-05-07 at 13 16 54" src="https://user-images.githubusercontent.com/86562400/236671585-ffa109be-477c-432f-be8b-2cef3180053b.png">
