### ISSUE TITLE
Detect second sharp object of interest with a +90% accuracy.  

### ISSUE THREAD

**Issue by Abdumbo99** [esattok/vanny#67]
Detect second sharp object of interest with a +90% accuracy.  child of #59

**Comment by esattok** [comment]
The images here are taken by integrating the model into the system and capturing the video via the camera of the laptop.

<img width="127" alt="Screen Shot 2023-05-07 at 13 15 58" src="https://user-images.githubusercontent.com/86562400/236671546-2c102e1c-3c97-49be-b0de-8e0337885f85.png">
